isatty() is declared in unistd.h.
Though it did not seem to be a problem on Linux, this broke compilation
when cross-compiling for Windows.
Fixes:
> error: implicit declaration of function 'isatty'